GET http://localhost:5250/games

###
GET http://localhost:5250/games/3

###
POST http://localhost:5250/games
content-type: application/json
{
  "name": "Final fantazy XIV",
  "genreId": 2,
  "price": 59.99,
  "releaseDate": "2010-09-30"
}

###
PUT http://localhost:5250/games/3
Content-Type: application/json
{
   
    "name": "Street Fighter II Turbo",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "1991-03-03"
  }

###
  DELETE http://localhost:5250/games/2